<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260912100751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE integer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT NOT NULL, sum INT NOT NULL, count INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE number (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT NOT NULL, search_target VARCHAR(100) NOT NULL, found_index VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, age INT NOT NULL, message VARCHAR(256) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE integer');
        $this->addSql('DROP TABLE number');
        $this->addSql('DROP TABLE "user"');
    }
}
